CARRIERS = {
    "TRANSPORTADORA GASODUTO BOLÍVIA-BRASIL S.A. - TBG": "01",
    "NOVA TRANSPORTADORA DO SUDESTE S.A. - NTS": "02",
    "TRANSPORTADORA ASSOCIADA DE GÁS S.A. - TAG": "03",
    "TRANSPORTADORA SULBRASILEIRA DE GÁS S.A. - TSB": "04",
    "GASOCIDENTE DO MATO GROSSO LTDA. - GOM": "05",
}