SELECT 
    z.ZONA AS zona,
    ip.PONTO AS nome_ponto,
    ip.MUNICIPIO AS municipio,
    ip.UF AS uf,
    g.NOME_DUTO AS nome_gasoduto
FROM 
    ZONA z
JOIN 
    INSTALACAO_PONTO ip ON z.COD_ZONA = ip.ZONA_COD_ZONA
JOIN 
    GASODUTO g ON ip.GASODUTO_COD_GASODUTO = g.COD_GASODUTO;


SELECT 
    ic.COD_INSTRUMENTO_CONTRATUAL AS numero_instrumento_contratual,
    t.NOME_REDUZIDO AS nome_transportador,
    c.NOME_REDUZIDO AS nome_carregador,
    tic.TIPO_INSTRUMENTO_CONTRATUAL AS tipo_instrumento_contratual,
    ic.DATA_ASSINATURA AS data_assinatura,
    ic.NUM_SEI_ORIGINAL AS documento_SEI,
    cm.DATA_INICIO AS data_inicio,
    cm.DATA_FIM AS data_fim
FROM 
    INSTRUMENTO_CONTRATUAL ic
JOIN 
    TRANSPORTADOR t ON ic.TRANSPORTADOR_COD_TRANSPORTADORA = t.COD_TRANSPORTADORA
JOIN 
    CARREGADOR c ON ic.CARREGADOR_COD_CARREGADOR = c.COD_CARREGADOR
JOIN 
    TIPO_INSTRUMENTO_CONTRATUAL tic ON ic.TIPO_INSTRUMENTO_CONTRATUAL_COD_TIPO_IC = tic.COD_TIPO_IC
JOIN 
    CONTRATO_MASTER cm ON ic.COD_INSTRUMENTO_CONTRATUAL = cm.INSTRUMENTO_CONTRATUAL_COD_INSTRUMENTO_CONTRATUAL
WHERE 
    tic.TIPO_INSTRUMENTO_CONTRATUAL = "CONTRATO MASTER";
    
    

SELECT 
    ic.COD_INSTRUMENTO_CONTRATUAL AS numero_instrumento_contratual,
    t.NOME_REDUZIDO AS nome_transportador,
    c.NOME_REDUZIDO AS nome_carregador,
    m.MODALIDADE AS modalidade,
    p.PERIODICIDADE AS periodicidade,
    ct.DATA_INICIO_SERVICO AS data_inicio_servico,
    ct.DATA_FIM_SERVICO AS data_fim_servico,
    cm.COD_MASTER AS codigo_contrato_master_relacionado,
    ic.DATA_ASSINATURA AS data_assinatura,
    ic.NUM_SEI_ORIGINAL AS numero_sei_original,
    q.QDC_MIL_M3_DIA AS qdc_em_mil_m3_dia,
    r.REGIME AS regime_contratacao,
    z.ZONA AS zona,
    ip.PONTO AS pontos
FROM 
    INSTRUMENTO_CONTRATUAL ic
JOIN 
    TRANSPORTADOR t ON ic.TRANSPORTADOR_COD_TRANSPORTADORA = t.COD_TRANSPORTADORA
JOIN 
    CARREGADOR c ON ic.CARREGADOR_COD_CARREGADOR = c.COD_CARREGADOR
JOIN 
    CONTRATO_TRANSPORTE ct ON ic.COD_INSTRUMENTO_CONTRATUAL = ct.INSTRUMENTO_CONTRATUAL_COD_INSTRUMENTO_CONTRATUAL
JOIN 
    MODALIDADE m ON ct.MODALIDADE_COD_MODALIDADE = m.COD_MODALIDADE
JOIN 
    PERIODICIDADE p ON ct.PERIODICIDADE_COD_PERIODICIDADE = p.COD_PERIODICIDADE
JOIN 
    CONTRATO_MASTER cm ON ct.CONTRATO_MASTER_COD_MASTER = cm.COD_MASTER
JOIN 
    QDC_has_INSTRUMENTO_CONTRATUAL qic ON ic.COD_INSTRUMENTO_CONTRATUAL = qic.INSTRUMENTO_CONTRATUAL_COD_INSTRUMENTO_CONTRATUAL
JOIN 
    QDC q ON qic.QDC_COD_QDC = q.COD_QDC
JOIN 
    REGIME_CONTRATACAO r ON q.REGIME_CONTRATACAO_COD_REGIME = r.COD_REGIME
JOIN 
    QDC_has_ZONA qz ON q.COD_QDC = qz.QDC_COD_QDC
JOIN 
    ZONA z ON qz.ZONA_COD_ZONA = z.COD_ZONA
JOIN 
    INSTALACAO_PONTO ip ON z.COD_ZONA = ip.ZONA_COD_ZONA
WHERE 
    ic.TIPO_INSTRUMENTO_CONTRATUAL_COD_TIPO_IC = (SELECT COD_TIPO_IC FROM TIPO_INSTRUMENTO_CONTRATUAL WHERE TIPO_INSTRUMENTO_CONTRATUAL = 'Contrato de Transporte');